### ISSUE TITLE
下拉组件样式问题

### ISSUE THREAD

**Issue by BoyuZhou** [tinper-bee/bee-select#2]
点击选择内容，出现阴影，再点击其他地方，阴影消失，但会在下拉框右边留下一个蓝色边，如图
![image](https://cloud.githubusercontent.com/assets/14073759/24391777/8a840978-13c3-11e7-954b-dc1e68abd101.png)

**Comment by lucian55** [comment]
README.md文档错误，如下图


![image](https://user-images.githubusercontent.com/17527649/30096899-6cd2f7da-930d-11e7-92df-344c042a0aba.png)

**Comment by ahua52** [comment]
已经修复
