### ISSUE TITLE
bee-select现在使用在bee-modal组件的时候，会被modal覆盖

### ISSUE THREAD

**Issue by HuYuee** [tinper-bee/bee-select#7]
原因：1. bee-select的下拉出来的列表并不是和输入框在同一个dom结构里，而是在body元素下append的一个元素，然后通过绝对定位，动态的定位到inpu框下。
2. 然后modal上面书写了样式z-index:1700;导致下拉列表的显示被覆盖

**Comment by BoyuZhou** [comment]
可以设置select的dropdownStyle={{zIndex:1800}}来处理

**Comment by HuYuee** [comment]
能不能通过，将下拉出来的列表，设计到和input框放在同一个父元素的设计方式，来解决这个问题

**Comment by BoyuZhou** [comment]
这个是我们一部分组件的思路，到时候整合一下
