### ISSUE TITLE
希望能提供【滚动条滑到底部】的钩子函数

### ISSUE THREAD

**Issue by lyx9439** [tinper-bee/bee-select#8]
希望能提供【滚动条滑到底部】的钩子函数，用来动态加载数据（加载下一页）

**Comment by lyx9439** [comment]
![_20171103142922](https://user-images.githubusercontent.com/25003211/32362334-6fadceb2-c0a3-11e7-946f-5ea56e0881ad.png)

**Comment by lyx9439** [comment]
其他问题：一、showSearch设置为true的时候，input的长度太短，父div的宽度没有设100%
二、搜索的时候会一直报错Uncaught TypeError: menu.onKeyDown is not a function

**Comment by HuYuee** [comment]
好的，需求和bug我们会尽快加上并修复。
